In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [3]:
data = pd.read_csv("Downloads\\Boston.CSV")

In [4]:
data.head()

crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [6]:
data.tail()

crim   zn  indus    nox     rm   age     dis  rad  tax  ptratio  \
501  0.06263  0.0  11.93  0.573  6.593  69.1  2.4786    1  273     21.0   
502  0.04527  0.0  11.93  0.573  6.120  76.7  2.2875    1  273     21.0   
503  0.06076  0.0  11.93  0.573  6.976  91.0  2.1675    1  273     21.0   
504  0.10959  0.0  11.93  0.573  6.794  89.3  2.3889    1  273     21.0   
505  0.04741  0.0  11.93  0.573  6.030  80.8  2.5050    1  273     21.0   

      black  lstat  medv  
501  391.99   9.67  22.4  
502  396.90   9.08  20.6  
503  396.90   5.64  23.9  
504  393.45   6.48  22.0  
505  396.90   7.88  11.9

In [14]:
x=data.iloc[:,:12].values

In [15]:
x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [16]:
y = data.iloc[:,12].values

In [17]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [25]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [29]:
model= LinearRegression()

In [30]:
# Train Model
model.fit(x_train,y_train)

LinearRegression()

In [31]:
model.intercept_

43.05414355323656

In [32]:
model.coef_

array([-1.16864610e-01,  5.89919351e-02,  3.13788055e-02, -1.89083776e+01,
        3.13767259e+00,  5.91799939e-03, -1.51102394e+00,  3.24766367e-01,
       -1.24228129e-02, -1.01509615e+00,  7.67905631e-03, -5.51889602e-01])

In [34]:
# R squared value (Capture the variation in this model)
model.score(x_train,y_train)*100

72.55484607372183

In [37]:
# x test data prediction
y_pred=model.predict(x_test)

In [39]:
MSE = mean_squared_error(y_pred,y_test)

In [40]:
MSE

24.178715197042827

In [41]:
RMSE = np.sqrt(MSE)

In [42]:
RMSE

4.9171856988569

In [43]:
# How can prediction 
arr = np.array([0.07,17.6,2.67,0.678,6.45,67.54,4.04,1,295,15.3,397.6,4.85])

In [44]:
arr

array([7.000e-02, 1.760e+01, 2.670e+00, 6.780e-01, 6.450e+00, 6.754e+01,
       4.040e+00, 1.000e+00, 2.950e+02, 1.530e+01, 3.976e+02, 4.850e+00])

In [45]:
arr.shape

(12,)

In [46]:
x.shape

(506, 12)

In [47]:
# arr one D array to two D array 
arr = np.array([0.07,17.6,2.67,0.678,6.45,67.54,4.04,1,295,15.3,397.6,4.85]).reshape(1,12)

In [49]:
# Now Check Prediction
model.predict(arr)

array([27.38686936])